### ISSUE TITLE
Integrate with symfony 2

### ISSUE THREAD

**Issue by tiacruz** [norkunas/onesignal-php-api#62]
Hello,

How integrate with symfony 2?

The bundle dizda/OnesignalApiBundle work with version 0.1.0 and i´m version 1 with Guzzle 6.

Thanks

**Comment by norkunas** [comment]
Hey @tiacruz,

You could use http://docs.php-http.org/en/latest/integrations/symfony-bundle.html and then register this library as a service and pass the httplug client.

```yml
httplug:
    clients:
        acme:
            factory: 'httplug.factory.guzzle6'

services:
    app.onesignal_config:
        class: OneSignal\Config
        calls:
            - ["setApplicationId", ["your_app_id"]]
            - ["setApplicationAuthKey", ["your_app_auth_key"]]
            - ["setUserAuthKey", ["your_auth_key"]]
    app.onesignal:
        class: OneSignal\OneSignal
        arguments:
            - "@app.onesignal_config"
            - "@httplug.client.acme"
```
